import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { getEffectiveOrgId } from '@/lib/tenant/context';
import { adminDb } from '@/lib/firebase-admin';
import { FieldValue } from 'firebase-admin/firestore';
import { isDemoRequest, demoResponse, demoNotAvailable } from '@/lib/demo-api';
import { generateAvatarUrl } from '@/lib/demo-data';

// Demo users with story data
const DEMO_STORY_USERS: Record<string, { firstName: string; lastName: string; hasGoal: boolean; hasTasks: boolean; hasDayClosed: boolean; }> = {
  'demo-user': { firstName: 'You', lastName: '', hasGoal: true, hasTasks: true, hasDayClosed: false },
  'demo-coach-user': { firstName: 'Adam', lastName: 'Coach', hasGoal: true, hasTasks: true, hasDayClosed: true },
  'demo-member-1': { firstName: 'Sarah', lastName: 'Miller', hasGoal: true, hasTasks: true, hasDayClosed: true },
  'demo-member-2': { firstName: 'Michael', lastName: 'Chen', hasGoal: true, hasTasks: true, hasDayClosed: false },
  'demo-member-3': { firstName: 'Emma', lastName: 'Thompson', hasGoal: true, hasTasks: true, hasDayClosed: true },
  'demo-member-4': { firstName: 'James', lastName: 'Wilson', hasGoal: true, hasTasks: false, hasDayClosed: false },
  'demo-member-5': { firstName: 'Lisa', lastName: 'Park', hasGoal: true, hasTasks: true, hasDayClosed: true },
};

// Generate mock story data for demo users
function generateDemoStoryData(userId: string) {
  const user = DEMO_STORY_USERS[userId] || { firstName: 'Demo', lastName: 'User', hasGoal: true, hasTasks: true, hasDayClosed: false };
  const fullName = `${user.firstName} ${user.lastName}`.trim();
  const today = new Date().toISOString().split('T')[0];
  
  // Mock tasks for stories
  const mockTasks = user.hasTasks ? [
    { id: 'task-1', title: 'Complete morning workout', status: 'completed', isPrivate: false },
    { id: 'task-2', title: 'Review weekly goals', status: 'completed', isPrivate: false },
    { id: 'task-3', title: 'Read 20 pages of new book', status: 'pending', isPrivate: false },
  ] : [];
  
  const completedTasks = mockTasks.filter(t => t.status === 'completed');
  
  // Build stories array for user-posted stories (including selfie for Coach Adam)
  const stories: Array<{
    id: string;
    type: 'user_post';
    authorId: string;
    imageUrl?: string;
    videoUrl?: string;
    caption?: string;
    expiresAt: string;
    createdAt: string;
  }> = [];
  
  // Add selfie story for Coach Adam
  if (userId === 'demo-coach-user') {
    stories.push({
      id: 'story-selfie-coach',
      type: 'user_post',
      authorId: userId,
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
      caption: 'Great workout this morning! 💪 Time to conquer the day.',
      expiresAt: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    });
  }
  
  // Add selfies for some squad members
  if (userId === 'demo-member-1') {
    stories.push({
      id: 'story-selfie-sarah',
      type: 'user_post',
      authorId: userId,
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop',
      caption: 'Crushing my goals one day at a time! 🎯',
      expiresAt: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    });
  }
  
  if (userId === 'demo-member-3') {
    stories.push({
      id: 'story-selfie-emma',
      type: 'user_post',
      authorId: userId,
      imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop',
      caption: 'Another productive day in the books! 📚',
      expiresAt: new Date(Date.now() + 16 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    });
  }

  // Coach Adam has specific story data matching useUserStories.ts
  const isCoachAdam = userId === 'demo-coach-user';
  const coachTasks = [
    { id: 't1', title: 'Review client progress reports', status: 'completed', isPrivate: false },
    { id: 't2', title: 'Prepare coaching session materials', status: 'completed', isPrivate: false },
    { id: 't3', title: 'Send weekly motivation emails', status: 'pending', isPrivate: false },
  ];
  const coachCompletedTasks = coachTasks.filter(t => t.status === 'completed');
  
  const finalTasks = isCoachAdam ? coachTasks : mockTasks;
  const finalCompletedTasks = isCoachAdam ? coachCompletedTasks : completedTasks;
  
  return {
    stories,
    autoGeneratedData: {
      tasks: finalTasks,
      goal: user.hasGoal ? {
        title: isCoachAdam ? 'Help 100 clients achieve their goals' : 'Build consistent habits and achieve my goals',
        targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        progress: 65,
        updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      } : null,
      hasDayClosed: user.hasDayClosed,
      completedTasks: user.hasDayClosed ? finalCompletedTasks : [],
      eveningCheckIn: user.hasDayClosed ? {
        emotionalState: 'energized',
        tasksCompleted: finalCompletedTasks.length,
        tasksTotal: finalTasks.length,
        completedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      } : null,
      hasWeekClosed: false,
      weeklyReflection: null,
      latestTaskTimestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      weekStartDate: today,
    },
    hasStory: true,
    user: {
      firstName: user.firstName,
      lastName: user.lastName,
      imageUrl: generateAvatarUrl(fullName),
    },
  };
}

/**
 * GET /api/stories
 * Get stories for a user (or current user if no userId specified)
 * Returns both user-posted stories (from Firestore) AND auto-generated story data (tasks, goals, check-ins)
 */
export async function GET(request: NextRequest) {
  try {
    // Demo mode: return mock story data
    const isDemo = await isDemoRequest();
    if (isDemo) {
      const { searchParams } = new URL(request.url);
      const targetUserId = searchParams.get('userId') || 'demo-user';
      
      // Generate demo story data based on user ID
      const demoStoryData = generateDemoStoryData(targetUserId);
      return demoResponse(demoStoryData);
    }
    
    const { userId: currentUserId } = await auth();

    if (!currentUserId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get org context
    const organizationId = await getEffectiveOrgId();
    if (!organizationId) {
      return NextResponse.json({ error: 'Organization context required' }, { status: 400 });
    }

    // Check if stories are enabled (separate from feed setting)
    // Default to true for backwards compatibility - stories are enabled unless explicitly disabled
    const orgSettingsDoc = await adminDb.collection('org_settings').doc(organizationId).get();
    const orgSettings = orgSettingsDoc.data();
    
    // storiesEnabled defaults to true if not explicitly set
    if (orgSettings?.storiesEnabled === false) {
      return NextResponse.json({ error: 'Stories not enabled for this organization' }, { status: 403 });
    }

    // Get target user ID from query params (or current user)
    const { searchParams } = new URL(request.url);
    const targetUserId = searchParams.get('userId') || currentUserId;
    const isOwnProfile = currentUserId === targetUserId;

    // Get user-posted stories from Firestore (24hr TTL)
    const now = new Date();
    const twentyFourHoursAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);
    
    let stories: Array<{
      id: string;
      type: 'user_post';
      authorId: string;
      imageUrl?: string;
      videoUrl?: string;
      caption?: string;
      expiresAt: string;
      createdAt: string;
    }> = [];
    
    try {
      // Query stories for this user and organization
      // Note: Firestore may require a composite index for this query
      // Created stories without timestamp comparison first, then filter in JS
      const storiesSnapshot = await adminDb
        .collection('feed_stories')
        .where('authorId', '==', targetUserId)
        .where('organizationId', '==', organizationId)
        .orderBy('createdAt', 'desc')
        .limit(50)
        .get();
      
      // Filter to last 24 hours in JavaScript to avoid index issues
      stories = storiesSnapshot.docs
        .map(doc => {
          const data = doc.data();
          const createdAt = data.createdAt?.toDate?.() || (data.createdAt ? new Date(data.createdAt) : null);
          
          return {
            id: doc.id,
            type: 'user_post' as const,
            authorId: data.authorId,
            imageUrl: data.imageUrl,
            videoUrl: data.videoUrl,
            caption: data.caption,
            expiresAt: data.expiresAt?.toDate?.()?.toISOString() || data.expiresAt,
            createdAt: createdAt?.toISOString() || new Date().toISOString(),
            _createdAtDate: createdAt,
          };
        })
        .filter(story => {
          if (!story._createdAtDate) return false;
          return story._createdAtDate >= twentyFourHoursAgo;
        })
        .map(({ _createdAtDate, ...rest }) => rest)
        .slice(0, 20);
    } catch (firestoreError) {
      console.error('[STORIES_GET] Firestore error:', firestoreError);
    }

    // ===== FETCH AUTO-GENERATED STORY DATA FROM FIREBASE =====
    const today = new Date().toISOString().split('T')[0];
    
    // Fetch user data (for profile info only, NOT goal data)
    const userDoc = await adminDb.collection('users').doc(targetUserId).get();
    const userData = userDoc.exists ? userDoc.data() : null;

    // MULTI-TENANCY: Fetch goal from org_memberships, not users collection
    // Goals are org-scoped to prevent cross-organization data leakage
    let orgGoalData: { goal?: string; goalTargetDate?: string; goalProgress?: number; goalCompleted?: boolean; goalUpdatedAt?: unknown } | null = null;
    const targetMembershipSnapshot = await adminDb.collection('org_memberships')
      .where('userId', '==', targetUserId)
      .where('organizationId', '==', organizationId)
      .limit(1)
      .get();
    
    if (!targetMembershipSnapshot.empty) {
      orgGoalData = targetMembershipSnapshot.docs[0].data();
    }

    // Check if user has an active goal (from org_memberships only)
    const hasActiveGoal = !!(orgGoalData?.goal && !orgGoalData?.goalCompleted);
    
    // Fetch today's focus tasks
    const tasksQuery = adminDb
      .collection('tasks')
      .where('userId', '==', targetUserId)
      .where('date', '==', today)
      .where('listType', '==', 'focus');

    const tasksSnapshot = await tasksQuery.get();
    const tasks = tasksSnapshot.docs.map(doc => {
      const data = doc.data();
      const isPrivate = data.isPrivate || false;
      return {
        id: doc.id,
        title: (!isOwnProfile && isPrivate) ? 'Private task' : (data.title || ''),
        status: data.status || 'pending',
        isPrivate,
      };
    });

    // Check if evening check-in is completed for today
    const eveningCheckInRef = adminDb
      .collection('users')
      .doc(targetUserId)
      .collection('eveningCheckins')
      .doc(today);
    const eveningCheckInDoc = await eveningCheckInRef.get();
    const eveningCheckInData = eveningCheckInDoc.exists ? eveningCheckInDoc.data() : null;
    const hasDayClosed = !!(eveningCheckInData?.completedAt);

    // Check if weekly reflection is completed for current week
    const nowDate = new Date();
    const day = nowDate.getDay();
    const diff = nowDate.getDate() - day + (day === 0 ? -6 : 1);
    const monday = new Date(nowDate);
    monday.setDate(diff);
    const weekId = monday.toISOString().split('T')[0];

    const weeklyReflectionRef = adminDb
      .collection('users')
      .doc(targetUserId)
      .collection('weeklyReflections')
      .doc(weekId);
    const weeklyReflectionDoc = await weeklyReflectionRef.get();
    const weeklyReflectionData = weeklyReflectionDoc.exists ? weeklyReflectionDoc.data() : null;
    const hasWeekClosed = !!(weeklyReflectionData?.completedAt);

    // Get completed tasks from snapshot or current data
    interface TaskSnapshot {
      id: string;
      title?: string;
      status?: string;
      isPrivate?: boolean;
    }
    let completedTasks: TaskSnapshot[] = [];
    
    if (hasDayClosed && eveningCheckInData?.completedTasksSnapshot?.length > 0) {
      completedTasks = eveningCheckInData.completedTasksSnapshot.map((task: TaskSnapshot) => {
        const isPrivate = task.isPrivate || false;
        return {
          id: task.id,
          title: (!isOwnProfile && isPrivate) ? 'Private task' : (task.title || ''),
          status: 'completed',
          isPrivate,
        };
      });
    } else {
      completedTasks = tasks.filter(t => t.status === 'completed');
    }

    // Get task timestamps for proper ordering
    const taskTimestamps = tasksSnapshot.docs.map(doc => {
      const data = doc.data();
      const createdAt = data.createdAt?.toDate?.() || (data.createdAt ? new Date(data.createdAt) : null);
      return createdAt?.toISOString() || null;
    }).filter(Boolean) as string[];
    const latestTaskTimestamp = taskTimestamps.length > 0 
      ? taskTimestamps.sort().reverse()[0] 
      : null;

    // Get goal timestamp (when it was last updated) - from org_memberships
    const goalUpdatedAt = (orgGoalData?.goalUpdatedAt as { toDate?: () => Date })?.toDate?.()?.toISOString() 
      || orgGoalData?.goalUpdatedAt as string
      || null;

    // Get evening check-in completion timestamp
    const eveningCheckInCompletedAt = eveningCheckInData?.completedAt?.toDate?.()?.toISOString() 
      || eveningCheckInData?.completedAt 
      || null;

    // Get weekly reflection completion timestamp
    const weeklyReflectionCompletedAt = weeklyReflectionData?.completedAt?.toDate?.()?.toISOString() 
      || weeklyReflectionData?.completedAt 
      || null;

    // Build auto-generated story data with timestamps
    const autoGeneratedData = {
      tasks,
      goal: hasActiveGoal ? {
        title: orgGoalData?.goal || '',
        targetDate: orgGoalData?.goalTargetDate || '',
        progress: orgGoalData?.goalProgress || 0,
        updatedAt: goalUpdatedAt,
      } : null,
      hasDayClosed,
      completedTasks,
      eveningCheckIn: hasDayClosed ? {
        emotionalState: eveningCheckInData?.emotionalState || 'steady',
        tasksCompleted: eveningCheckInData?.tasksCompleted || 0,
        tasksTotal: eveningCheckInData?.tasksTotal || 0,
        completedAt: eveningCheckInCompletedAt,
      } : null,
      hasWeekClosed,
      weeklyReflection: hasWeekClosed ? {
        progressChange: (weeklyReflectionData?.progress || 0) - (weeklyReflectionData?.previousProgress || 0),
        publicFocus: weeklyReflectionData?.publicFocus || undefined,
        completedAt: weeklyReflectionCompletedAt,
      } : null,
      // Timestamps for slide ordering
      latestTaskTimestamp,
      weekStartDate: weekId, // Monday of current week
    };

    // Determine if user has any story content
    const hasStory = stories.length > 0 || 
                     tasks.length > 0 || 
                     hasActiveGoal || 
                     hasDayClosed || 
                     hasWeekClosed;

    return NextResponse.json({ 
      stories, 
      autoGeneratedData,
      hasStory,
      user: userData ? {
        firstName: userData.firstName || '',
        lastName: userData.lastName || '',
        imageUrl: userData.avatarUrl || userData.imageUrl || '',
      } : null,
    });
  } catch (error) {
    console.error('[STORIES_GET] Error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch stories' },
      { status: 500 }
    );
  }
}

/**
 * POST /api/stories
 * Create a new user-posted story (24hr ephemeral)
 * Stories are stored in Firestore with automatic expiration
 */
export async function POST(request: NextRequest) {
  try {
    // Demo mode: block story creation
    const isDemo = await isDemoRequest();
    if (isDemo) {
      return demoNotAvailable('Creating stories');
    }
    
    const { userId } = await auth();

    if (!userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get org context
    const organizationId = await getEffectiveOrgId();
    if (!organizationId) {
      return NextResponse.json({ error: 'Organization context required' }, { status: 400 });
    }

    // Check if stories are enabled (separate from feed setting)
    // Default to true for backwards compatibility
    const orgSettingsDoc = await adminDb.collection('org_settings').doc(organizationId).get();
    const orgSettings = orgSettingsDoc.data();
    
    // storiesEnabled defaults to true if not explicitly set
    if (orgSettings?.storiesEnabled === false) {
      return NextResponse.json({ error: 'Stories not enabled for this organization' }, { status: 403 });
    }

    // Parse request body
    const body = await request.json();
    const { imageUrl, videoUrl, caption } = body;

    // Validate - must have image or video
    if (!imageUrl && !videoUrl) {
      return NextResponse.json(
        { error: 'Story must have an image or video' },
        { status: 400 }
      );
    }

    // Calculate expiry (24 hours from now)
    const now = new Date();
    const expiresAt = new Date(now.getTime() + 24 * 60 * 60 * 1000);

    // Create story document in Firestore
    const storyData = {
      authorId: userId,
      organizationId,
      imageUrl: imageUrl || null,
      videoUrl: videoUrl || null,
      caption: caption || null,
      createdAt: FieldValue.serverTimestamp(),
      expiresAt,
    };

    const storyRef = await adminDb.collection('feed_stories').add(storyData);

    return NextResponse.json({
      success: true,
      story: {
        id: storyRef.id,
        type: 'user_post',
        authorId: userId,
        imageUrl,
        videoUrl,
        caption,
        expiresAt: expiresAt.toISOString(),
        createdAt: now.toISOString(),
      },
    });
  } catch (error) {
    console.error('[STORIES_POST] Error:', error);
    return NextResponse.json(
      { error: 'Failed to create story' },
      { status: 500 }
    );
  }
}
