'use client';

import { useState, useEffect, useCallback, useMemo } from 'react';
import type { StorySlide } from '@/components/stories/StoryPlayer';
import type { Task } from '@/types';
import { useDemoMode } from '@/contexts/DemoModeContext';
import { generateAvatarUrl } from '@/lib/demo-data';

// =============================================================================
// DEMO MODE MOCK DATA
// =============================================================================

// Helper to create a minimal Task object for demo
function createDemoTask(id: string, title: string, status: 'pending' | 'completed'): Task {
  return {
    id,
    userId: 'demo-user',
    organizationId: 'demo-org',
    title,
    status,
    listType: 'focus',
    order: 0,
    date: new Date().toISOString().split('T')[0],
    isPrivate: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

const DEMO_STORY_DATA: Record<string, { slides: StorySlide[], userPostedStories: UserPostedStory[], autoGeneratedData: AutoGeneratedStoryData }> = {
  'demo-coach-user': {
    slides: [
      {
        id: 'goal',
        type: 'goal',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        data: {
          goalTitle: 'Help 100 clients achieve their goals',
          targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
          progress: 65,
        },
      },
      {
        id: 'tasks',
        type: 'tasks',
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        data: {
          tasks: [
            createDemoTask('t1', 'Review client progress reports', 'completed'),
            createDemoTask('t2', 'Prepare coaching session materials', 'completed'),
            createDemoTask('t3', 'Send weekly motivation emails', 'pending'),
          ],
        },
      },
      {
        id: 'dayClosed',
        type: 'dayClosed',
        timestamp: new Date().toISOString(),
        data: {
          completedTasks: [
            createDemoTask('t1', 'Review client progress reports', 'completed'),
            createDemoTask('t2', 'Prepare coaching session materials', 'completed'),
          ],
          tasksCompleted: 2,
          tasksTotal: 3,
        },
      },
      {
        id: 'user_post_selfie',
        type: 'user_post',
        timestamp: new Date(Date.now() + 1000).toISOString(),
        data: {
          imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
          caption: 'Great workout this morning! 💪 Time to conquer the day.',
          createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
          expiresAt: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
        },
      },
    ],
    userPostedStories: [{
      id: 'story-selfie-coach',
      type: 'user_post',
      authorId: 'demo-coach-user',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
      caption: 'Great workout this morning! 💪 Time to conquer the day.',
      expiresAt: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    }],
    autoGeneratedData: {
      tasks: [
        createDemoTask('t1', 'Review client progress reports', 'completed'),
        createDemoTask('t2', 'Prepare coaching session materials', 'completed'),
        createDemoTask('t3', 'Send weekly motivation emails', 'pending'),
      ],
      goal: { title: 'Help 100 clients achieve their goals', targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(), progress: 65 },
      hasDayClosed: true,
      completedTasks: [
        createDemoTask('t1', 'Review client progress reports', 'completed'),
        createDemoTask('t2', 'Prepare coaching session materials', 'completed'),
      ],
      eveningCheckIn: { emotionalState: 'energized', tasksCompleted: 2, tasksTotal: 3 },
      hasWeekClosed: false,
      weeklyReflection: null,
    },
  },
  'demo-member-1': {
    slides: [
      {
        id: 'goal',
        type: 'goal',
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        data: {
          goalTitle: 'Build a successful coaching business',
          targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
          progress: 45,
        },
      },
      {
        id: 'tasks',
        type: 'tasks',
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        data: {
          tasks: [
            createDemoTask('t1', 'Morning meditation 10 min', 'completed'),
            createDemoTask('t2', 'Work on business plan', 'completed'),
            createDemoTask('t3', 'Network with 2 new contacts', 'pending'),
          ],
        },
      },
      {
        id: 'dayClosed',
        type: 'dayClosed',
        timestamp: new Date().toISOString(),
        data: {
          completedTasks: [
            createDemoTask('t1', 'Morning meditation 10 min', 'completed'),
            createDemoTask('t2', 'Work on business plan', 'completed'),
          ],
          tasksCompleted: 2,
          tasksTotal: 3,
        },
      },
      {
        id: 'user_post_selfie',
        type: 'user_post',
        timestamp: new Date(Date.now() + 1000).toISOString(),
        data: {
          imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop',
          caption: 'Crushing my goals one day at a time! 🎯',
          createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
          expiresAt: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
        },
      },
    ],
    userPostedStories: [{
      id: 'story-selfie-sarah',
      type: 'user_post',
      authorId: 'demo-member-1',
      imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=600&fit=crop',
      caption: 'Crushing my goals one day at a time! 🎯',
      expiresAt: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    }],
    autoGeneratedData: {
      tasks: [
        createDemoTask('t1', 'Morning meditation 10 min', 'completed'),
        createDemoTask('t2', 'Work on business plan', 'completed'),
        createDemoTask('t3', 'Network with 2 new contacts', 'pending'),
      ],
      goal: { title: 'Build a successful coaching business', targetDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(), progress: 45 },
      hasDayClosed: true,
      completedTasks: [
        createDemoTask('t1', 'Morning meditation 10 min', 'completed'),
        createDemoTask('t2', 'Work on business plan', 'completed'),
      ],
      eveningCheckIn: { emotionalState: 'calm', tasksCompleted: 2, tasksTotal: 3 },
      hasWeekClosed: false,
      weeklyReflection: null,
    },
  },
  'demo-member-2': {
    slides: [
      {
        id: 'goal',
        type: 'goal',
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        data: {
          goalTitle: 'Launch my SaaS product',
          targetDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
          progress: 45,
        },
      },
      {
        id: 'tasks',
        type: 'tasks',
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        data: {
          tasks: [
            createDemoTask('t1', 'Code landing page', 'completed'),
            createDemoTask('t2', 'Set up payment integration', 'completed'),
            createDemoTask('t3', 'Write launch email', 'completed'),
            createDemoTask('t4', 'Test checkout flow', 'pending'),
          ],
        },
      },
    ],
    userPostedStories: [],
    autoGeneratedData: {
      tasks: [
        createDemoTask('t1', 'Code landing page', 'completed'),
        createDemoTask('t2', 'Set up payment integration', 'completed'),
        createDemoTask('t3', 'Write launch email', 'completed'),
        createDemoTask('t4', 'Test checkout flow', 'pending'),
      ],
      goal: { title: 'Launch my SaaS product', targetDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(), progress: 45 },
      hasDayClosed: false,
      completedTasks: [],
      eveningCheckIn: null,
      hasWeekClosed: false,
      weeklyReflection: null,
    },
  },
  'demo-member-3': {
    slides: [
      {
        id: 'goal',
        type: 'goal',
        timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
        data: {
          goalTitle: 'Write my first book',
          targetDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(),
          progress: 30,
        },
      },
      {
        id: 'tasks',
        type: 'tasks',
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        data: {
          tasks: [
            createDemoTask('t1', 'Write 1000 words', 'completed'),
            createDemoTask('t2', 'Research chapter 5', 'completed'),
            createDemoTask('t3', 'Outline next chapter', 'pending'),
          ],
        },
      },
      {
        id: 'dayClosed',
        type: 'dayClosed',
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        data: {
          completedTasks: [
            createDemoTask('t1', 'Write 1000 words', 'completed'),
            createDemoTask('t2', 'Research chapter 5', 'completed'),
          ],
          tasksCompleted: 2,
          tasksTotal: 3,
        },
      },
      {
        id: 'user_post_selfie',
        type: 'user_post',
        timestamp: new Date(Date.now() + 1000).toISOString(),
        data: {
          imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop',
          caption: 'Another productive day in the books! 📚',
          createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
          expiresAt: new Date(Date.now() + 16 * 60 * 60 * 1000).toISOString(),
        },
      },
    ],
    userPostedStories: [{
      id: 'story-selfie-emma',
      type: 'user_post',
      authorId: 'demo-member-3',
      imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=600&fit=crop',
      caption: 'Another productive day in the books! 📚',
      expiresAt: new Date(Date.now() + 16 * 60 * 60 * 1000).toISOString(),
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    }],
    autoGeneratedData: {
      tasks: [
        createDemoTask('t1', 'Write 1000 words', 'completed'),
        createDemoTask('t2', 'Research chapter 5', 'completed'),
        createDemoTask('t3', 'Outline next chapter', 'pending'),
      ],
      goal: { title: 'Write my first book', targetDate: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000).toISOString(), progress: 30 },
      hasDayClosed: true,
      completedTasks: [
        createDemoTask('t1', 'Write 1000 words', 'completed'),
        createDemoTask('t2', 'Research chapter 5', 'completed'),
      ],
      eveningCheckIn: { emotionalState: 'reflective', tasksCompleted: 2, tasksTotal: 3 },
      hasWeekClosed: false,
      weeklyReflection: null,
    },
  },
  'demo-member-5': {
    slides: [
      {
        id: 'goal',
        type: 'goal',
        timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        data: {
          goalTitle: 'Learn a new language',
          targetDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(),
          progress: 15,
        },
      },
      {
        id: 'tasks',
        type: 'tasks',
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        data: {
          tasks: [
            createDemoTask('t1', 'Duolingo lesson', 'completed'),
            createDemoTask('t2', 'Practice speaking 15 min', 'completed'),
            createDemoTask('t3', 'Watch foreign film', 'pending'),
          ],
        },
      },
      {
        id: 'dayClosed',
        type: 'dayClosed',
        timestamp: new Date().toISOString(),
        data: {
          completedTasks: [
            createDemoTask('t1', 'Duolingo lesson', 'completed'),
            createDemoTask('t2', 'Practice speaking 15 min', 'completed'),
          ],
          tasksCompleted: 2,
          tasksTotal: 3,
        },
      },
    ],
    userPostedStories: [],
    autoGeneratedData: {
      tasks: [
        createDemoTask('t1', 'Duolingo lesson', 'completed'),
        createDemoTask('t2', 'Practice speaking 15 min', 'completed'),
        createDemoTask('t3', 'Watch foreign film', 'pending'),
      ],
      goal: { title: 'Learn a new language', targetDate: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString(), progress: 15 },
      hasDayClosed: true,
      completedTasks: [
        createDemoTask('t1', 'Duolingo lesson', 'completed'),
        createDemoTask('t2', 'Practice speaking 15 min', 'completed'),
      ],
      eveningCheckIn: { emotionalState: 'motivated', tasksCompleted: 2, tasksTotal: 3 },
      hasWeekClosed: false,
      weeklyReflection: null,
    },
  },
};

// =============================================================================
// TYPES
// =============================================================================

export interface UserPostedStory {
  id: string;
  type: 'user_post';
  authorId: string;
  imageUrl?: string;
  videoUrl?: string;
  caption?: string;
  expiresAt: string;
  createdAt: string;
}

export interface AutoGeneratedStoryData {
  tasks: Task[];
  goal: {
    title: string;
    targetDate: string;
    progress: number;
    updatedAt?: string | null;
  } | null;
  hasDayClosed: boolean;
  completedTasks: Task[];
  eveningCheckIn: {
    emotionalState: string;
    tasksCompleted: number;
    tasksTotal: number;
    completedAt?: string | null;
  } | null;
  hasWeekClosed: boolean;
  weeklyReflection: {
    progressChange: number;
    publicFocus?: string;
    completedAt?: string | null;
  } | null;
  // Timestamps for chronological ordering
  latestTaskTimestamp?: string | null;
  weekStartDate?: string;
}

export interface MergedStoryData {
  userPostedStories: UserPostedStory[];
  autoGeneratedData: AutoGeneratedStoryData | null;
  slides: StorySlide[];
  hasStory: boolean;
  isLoading: boolean;
  error: string | null;
}

// =============================================================================
// HOOK
// =============================================================================

/**
 * Hook to fetch and merge stories from both sources:
 * - User-posted stories from Firestore (ephemeral, 24hr)
 * - Auto-generated stories from Firebase (tasks, goals, check-ins)
 * 
 * Returns a unified array of StorySlide[] for the StoryPlayer.
 * 
 * The API now returns both sources in one call, so we don't need
 * firebaseStoryData passed in separately.
 * 
 * In Demo Mode: Returns mock story data without making network requests.
 */
export function useUserStories(userId: string): MergedStoryData {
  const { isDemoMode } = useDemoMode();
  const [userPostedStories, setUserPostedStories] = useState<UserPostedStory[]>([]);
  const [autoGeneratedData, setAutoGeneratedData] = useState<AutoGeneratedStoryData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Demo mode: return mock story data immediately
  const demoData = useMemo(() => {
    if (!isDemoMode || !userId) return null;
    return DEMO_STORY_DATA[userId] || null;
  }, [isDemoMode, userId]);

  // Early return for demo mode
  if (isDemoMode && demoData) {
    return {
      userPostedStories: demoData.userPostedStories,
      autoGeneratedData: demoData.autoGeneratedData,
      slides: demoData.slides,
      hasStory: demoData.slides.length > 0,
      isLoading: false,
      error: null,
    };
  }

  // Reset loading state immediately when userId changes
  useEffect(() => {
    if (isDemoMode) return; // Skip in demo mode
    if (userId) {
      setIsLoading(true);
      setUserPostedStories([]);
      setAutoGeneratedData(null);
    } else {
      setIsLoading(false);
    }
  }, [userId, isDemoMode]);

  // Fetch all stories (user-posted + auto-generated) from API
  const fetchStories = useCallback(async () => {
    if (!userId || isDemoMode) {
      return;
    }

    try {
      const response = await fetch(`/api/stories?userId=${userId}`);
      
      if (response.status === 403) {
        // Feed not enabled - no stories
        setUserPostedStories([]);
        setAutoGeneratedData(null);
        return;
      }
      
      if (!response.ok) {
        throw new Error('Failed to fetch stories');
      }

      const data = await response.json();
      setUserPostedStories(data.stories || []);
      setAutoGeneratedData(data.autoGeneratedData || null);
      setError(null);
    } catch (err) {
      console.error('[useUserStories] Error fetching stories:', err);
      setError(err instanceof Error ? err.message : 'Failed to fetch stories');
      setUserPostedStories([]);
      setAutoGeneratedData(null);
    } finally {
      setIsLoading(false);
    }
  }, [userId, isDemoMode]);

  // Fetch on mount and when userId changes (skip in demo mode)
  useEffect(() => {
    if (userId && !isDemoMode) {
      fetchStories();
    }
  }, [userId, isDemoMode, fetchStories]);

  // Build merged slides array in CHRONOLOGICAL order (oldest first, newest last)
  // All slides have timestamps and are sorted together for proper ordering
  const slides = useMemo(() => {
    const allSlides: StorySlide[] = [];
    const now = new Date().toISOString();
    
    // Get week start (Monday) for goal timestamp fallback
    const getWeekStart = (): string => {
      const nowDate = new Date();
      const day = nowDate.getDay();
      const diff = nowDate.getDate() - day + (day === 0 ? -6 : 1);
      const monday = new Date(nowDate);
      monday.setDate(diff);
      monday.setHours(0, 0, 0, 0);
      return monday.toISOString();
    };

    if (autoGeneratedData) {
      // Goal slide - timestamp based on updatedAt or week start
      // Goal is "new" if it was updated this week or if the week changed
      if (autoGeneratedData.goal) {
        const weekStart = autoGeneratedData.weekStartDate 
          ? new Date(autoGeneratedData.weekStartDate + 'T00:00:00').toISOString()
          : getWeekStart();
        
        // Use goal's updatedAt if available and newer than week start, otherwise use week start
        let goalTimestamp = weekStart;
        if (autoGeneratedData.goal.updatedAt) {
          const updatedAt = new Date(autoGeneratedData.goal.updatedAt);
          const weekStartDate = new Date(weekStart);
          if (updatedAt > weekStartDate) {
            goalTimestamp = autoGeneratedData.goal.updatedAt;
          }
        }
        
        allSlides.push({
          id: 'goal',
          type: 'goal',
          timestamp: goalTimestamp,
          data: {
            goalTitle: autoGeneratedData.goal.title,
            targetDate: autoGeneratedData.goal.targetDate,
            progress: autoGeneratedData.goal.progress,
          },
        });
      }

      // Tasks slide - timestamp based on most recent task
      if (autoGeneratedData.tasks && autoGeneratedData.tasks.length > 0) {
        const taskTimestamp = autoGeneratedData.latestTaskTimestamp || now;
        allSlides.push({
          id: 'tasks',
          type: 'tasks',
          timestamp: taskTimestamp,
          data: { tasks: autoGeneratedData.tasks },
        });
      }

      // Day Closed slide - timestamp from evening check-in
      if (autoGeneratedData.hasDayClosed) {
        const actualCompletedTasks = autoGeneratedData.completedTasks?.length > 0 
          ? autoGeneratedData.completedTasks 
          : (autoGeneratedData.tasks || []).filter(t => t.status === 'completed');
        
        const dayClosedTimestamp = autoGeneratedData.eveningCheckIn?.completedAt || now;
        allSlides.push({
          id: 'dayClosed',
          type: 'dayClosed',
          timestamp: dayClosedTimestamp,
          data: {
            completedTasks: actualCompletedTasks,
            tasksCompleted: autoGeneratedData.eveningCheckIn?.tasksCompleted || actualCompletedTasks.length,
            tasksTotal: autoGeneratedData.eveningCheckIn?.tasksTotal || (autoGeneratedData.tasks?.length || 0),
          },
        });
      }

      // Week Closed slide - timestamp from weekly reflection
      if (autoGeneratedData.hasWeekClosed && autoGeneratedData.weeklyReflection) {
        const weekClosedTimestamp = autoGeneratedData.weeklyReflection.completedAt || now;
        allSlides.push({
          id: 'weekClosed',
          type: 'weekClosed',
          timestamp: weekClosedTimestamp,
          data: {
            progressChange: autoGeneratedData.weeklyReflection.progressChange,
            publicFocus: autoGeneratedData.weeklyReflection.publicFocus,
          },
        });
      }
    }

    // User-posted stories with their createdAt as timestamp
    userPostedStories.forEach((story) => {
      allSlides.push({
        id: story.id,
        type: 'user_post',
        timestamp: story.createdAt,
        data: {
          imageUrl: story.imageUrl,
          videoUrl: story.videoUrl,
          caption: story.caption,
          createdAt: story.createdAt,
          expiresAt: story.expiresAt,
        },
      });
    });

    // Sort all slides by timestamp (oldest first, newest last)
    allSlides.sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());

    return allSlides;
  }, [userPostedStories, autoGeneratedData]);

  // Determine if user has any story
  const hasStory = slides.length > 0;

  return {
    userPostedStories,
    autoGeneratedData,
    slides,
    hasStory,
    isLoading,
    error,
  };
}

/**
 * Hook for the current user to create stories
 */
export function useCreateStory() {
  const [isCreating, setIsCreating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const createStory = useCallback(async (data: {
    imageUrl?: string;
    videoUrl?: string;
    caption?: string;
  }) => {
    setIsCreating(true);
    setError(null);

    try {
      const response = await fetch('/api/stories', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to create story');
      }

      const result = await response.json();
      return result.story as UserPostedStory;
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to create story';
      setError(errorMessage);
      throw err;
    } finally {
      setIsCreating(false);
    }
  }, []);

  return {
    createStory,
    isCreating,
    error,
  };
}

/**
 * Simplified hook to check if any user in an array has stories
 * Used for the story avatar row to show which users have content
 */
export function useMultipleUserStories(userIds: string[]) {
  const [storiesMap, setStoriesMap] = useState<Map<string, boolean>>(new Map());
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchAll = async () => {
      if (userIds.length === 0) {
        setIsLoading(false);
        return;
      }

      const results = new Map<string, boolean>();
      
      // Fetch in parallel (batch of 5 at a time to avoid overwhelming)
      const batches = [];
      for (let i = 0; i < userIds.length; i += 5) {
        batches.push(userIds.slice(i, i + 5));
      }

      for (const batch of batches) {
        await Promise.all(
          batch.map(async (userId) => {
            try {
              const response = await fetch(`/api/stories?userId=${userId}`);
              if (response.ok) {
                const data = await response.json();
                // hasStory includes both user-posted AND auto-generated stories
                results.set(userId, data.hasStory === true);
              } else {
                results.set(userId, false);
              }
            } catch {
              results.set(userId, false);
            }
          })
        );
      }

      setStoriesMap(results);
      setIsLoading(false);
    };

    fetchAll();
  }, [userIds.join(',')]); // Re-run when user list changes

  return {
    storiesMap,
    isLoading,
    hasStory: (userId: string) => storiesMap.get(userId) || false,
  };
}

